//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Site", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuộc Chuyên mục.
        /// </summary>
        internal static string ArticleBelongTopic {
            get {
                return ResourceManager.GetString("ArticleBelongTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục chính.
        /// </summary>
        internal static string ArticleBelongTopicPrimary {
            get {
                return ResourceManager.GetString("ArticleBelongTopicPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển Chuyên mục chính.
        /// </summary>
        internal static string ArticleChangeTopicPrimary {
            get {
                return ResourceManager.GetString("ArticleChangeTopicPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết chỉ có một chuyên mục !.
        /// </summary>
        internal static string ArticleChangeTopicPrimaryOnlyOne {
            get {
                return ResourceManager.GetString("ArticleChangeTopicPrimaryOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển Chuyên mục cho Bài viết thành công.
        /// </summary>
        internal static string ArticleChangeTopicPrimarySuccess {
            get {
                return ResourceManager.GetString("ArticleChangeTopicPrimarySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa bài viết này?.
        /// </summary>
        internal static string ArticleConfirmDelete {
            get {
                return ResourceManager.GetString("ArticleConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung Bài viết.
        /// </summary>
        internal static string ArticleContent {
            get {
                return ResourceManager.GetString("ArticleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả Bài viết.
        /// </summary>
        internal static string ArticleDescription {
            get {
                return ResourceManager.GetString("ArticleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết Bài viết.
        /// </summary>
        internal static string ArticleDetail {
            get {
                return ResourceManager.GetString("ArticleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu chỉnh Nội dung.
        /// </summary>
        internal static string ArticleEditContent {
            get {
                return ResourceManager.GetString("ArticleEditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu chỉnh Mô tả.
        /// </summary>
        internal static string ArticleEditDescription {
            get {
                return ResourceManager.GetString("ArticleEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu chỉnh Chuyên mục.
        /// </summary>
        internal static string ArticleEditTopic {
            get {
                return ResourceManager.GetString("ArticleEditTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài Viết.
        /// </summary>
        internal static string ArticleManage {
            get {
                return ResourceManager.GetString("ArticleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Bài viết.
        /// </summary>
        internal static string ArticleNotChoose {
            get {
                return ResourceManager.GetString("ArticleNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Article.
        /// </summary>
        internal static string ArticleSelect {
            get {
                return ResourceManager.GetString("ArticleSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu chỉnh Chuyên mục cho Bài viết.
        /// </summary>
        internal static string ArticleTopic {
            get {
                return ResourceManager.GetString("ArticleTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nội dung cho Bài viết thành công!.
        /// </summary>
        internal static string ArticleUpdateContentSuccess {
            get {
                return ResourceManager.GetString("ArticleUpdateContentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật mô tả cho Bài viết thành công!.
        /// </summary>
        internal static string ArticleUpdateDescriptionSuccess {
            get {
                return ResourceManager.GetString("ArticleUpdateDescriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chuyên mục cho Bài viết thành công!.
        /// </summary>
        internal static string ArticleUpdateTopicSuccess {
            get {
                return ResourceManager.GetString("ArticleUpdateTopicSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết chưa chọn chuyên mục chính.
        /// </summary>
        internal static string AticleNoBelongTopicPrimary {
            get {
                return ResourceManager.GetString("AticleNoBelongTopicPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác nhận.
        /// </summary>
        internal static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu chỉnh nhóm.
        /// </summary>
        internal static string ChangeGroup {
            get {
                return ResourceManager.GetString("ChangeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi giao diện.
        /// </summary>
        internal static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu chỉnh người dùng.
        /// </summary>
        internal static string ChangeUser {
            get {
                return ResourceManager.GetString("ChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin video (.flv).
        /// </summary>
        internal static string ClipFileUpLoad {
            get {
                return ResourceManager.GetString("ClipFileUpLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa clip tin tức.
        /// </summary>
        internal static string ClipNewsConfirmDelete {
            get {
                return ResourceManager.GetString("ClipNewsConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        internal static string ClipNewsDeleteSuccess {
            get {
                return ResourceManager.GetString("ClipNewsDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải.
        /// </summary>
        internal static string ClipNewsDescription {
            get {
                return ResourceManager.GetString("ClipNewsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết clip tin tức.
        /// </summary>
        internal static string ClipNewsDetail {
            get {
                return ResourceManager.GetString("ClipNewsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn file tải lên.
        /// </summary>
        internal static string ClipNewsFileUpLoadNotchoose {
            get {
                return ResourceManager.GetString("ClipNewsFileUpLoadNotchoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip tin tức.
        /// </summary>
        internal static string ClipNewsManage {
            get {
                return ResourceManager.GetString("ClipNewsManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn clip tin tức.
        /// </summary>
        internal static string ClipNewsNotChoose {
            get {
                return ResourceManager.GetString("ClipNewsNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Góp ý.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Nội dung.
        /// </summary>
        internal static string ContentManagement {
            get {
                return ResourceManager.GetString("ContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sử dụng bởi PSC Portal.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ngày.
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa Phòng ban này?.
        /// </summary>
        internal static string DepartmentConfirmDelete {
            get {
                return ResourceManager.GetString("DepartmentConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết Phòng ban.
        /// </summary>
        internal static string DepartmentDetail {
            get {
                return ResourceManager.GetString("DepartmentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Phòng ban!.
        /// </summary>
        internal static string DepartmentNotChoose {
            get {
                return ResourceManager.GetString("DepartmentNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả không được rỗng!.
        /// </summary>
        internal static string DescriptionCanNotEmpty {
            get {
                return ResourceManager.GetString("DescriptionCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu thuộc loại.
        /// </summary>
        internal static string DocumentBelongDocumentType {
            get {
                return ResourceManager.GetString("DocumentBelongDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loai tài liệu chính.
        /// </summary>
        internal static string DocumentBelongDocumentTypePrimary {
            get {
                return ResourceManager.GetString("DocumentBelongDocumentTypePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển loại tài liệu chính.
        /// </summary>
        internal static string DocumentChangeDocumentTypePrimary {
            get {
                return ResourceManager.GetString("DocumentChangeDocumentTypePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu chỉ thuộc một loại tài liệu!.
        /// </summary>
        internal static string DocumentChangeDocumentTypePrimaryOnlyOne {
            get {
                return ResourceManager.GetString("DocumentChangeDocumentTypePrimaryOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển loại tài liệu chính thành công!.
        /// </summary>
        internal static string DocumentChangeDocumentTypePrimarySuccess {
            get {
                return ResourceManager.GetString("DocumentChangeDocumentTypePrimarySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa tài liệu này?.
        /// </summary>
        internal static string DocumentConfirmDelete {
            get {
                return ResourceManager.GetString("DocumentConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết văn bản.
        /// </summary>
        internal static string DocumentDetail {
            get {
                return ResourceManager.GetString("DocumentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu chỉnh loại cho tài liệu.
        /// </summary>
        internal static string DocumentDocumentType {
            get {
                return ResourceManager.GetString("DocumentDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Loại tài liệu.
        /// </summary>
        internal static string DocumentEditType {
            get {
                return ResourceManager.GetString("DocumentEditType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu.
        /// </summary>
        internal static string DocumentManage {
            get {
                return ResourceManager.GetString("DocumentManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Tài liệu.
        /// </summary>
        internal static string DocumentManagement {
            get {
                return ResourceManager.GetString("DocumentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu chưa chọn loại tài liệu chính.
        /// </summary>
        internal static string DocumentNoBelongDocumentTypePrimary {
            get {
                return ResourceManager.GetString("DocumentNoBelongDocumentTypePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn tài liệu!.
        /// </summary>
        internal static string DocumentNotChoose {
            get {
                return ResourceManager.GetString("DocumentNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tài liệu.
        /// </summary>
        internal static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa loại tài  liệu này?.
        /// </summary>
        internal static string DocumentTypeConfirmDelete {
            get {
                return ResourceManager.GetString("DocumentTypeConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết loại tài liệu.
        /// </summary>
        internal static string DocumentTypeDetail {
            get {
                return ResourceManager.GetString("DocumentTypeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tài liệu.
        /// </summary>
        internal static string DocumentTypeManage {
            get {
                return ResourceManager.GetString("DocumentTypeManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn loại tài liệu!.
        /// </summary>
        internal static string DocumentTypeNotChoose {
            get {
                return ResourceManager.GetString("DocumentTypeNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn loại tài liệu.
        /// </summary>
        internal static string DocumentTypeSelect {
            get {
                return ResourceManager.GetString("DocumentTypeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật loại tài liệu cho tài liệu thành công!.
        /// </summary>
        internal static string DocumentUpdateTypeSuccess {
            get {
                return ResourceManager.GetString("DocumentUpdateTypeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu chỉnh.
        /// </summary>
        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File hiển thị.
        /// </summary>
        internal static string FileDisplay {
            get {
                return ResourceManager.GetString("FileDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File download.
        /// </summary>
        internal static string FileDownload {
            get {
                return ResourceManager.GetString("FileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm có quyền.
        /// </summary>
        internal static string GrantGroupList {
            get {
                return ResourceManager.GetString("GrantGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        internal static string GrantItem {
            get {
                return ResourceManager.GetString("GrantItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm thuộc người dùng.
        /// </summary>
        internal static string GroupBelongUser {
            get {
                return ResourceManager.GetString("GroupBelongUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa Nhóm này?.
        /// </summary>
        internal static string GroupConfirmDelete {
            get {
                return ResourceManager.GetString("GroupConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết Nhóm.
        /// </summary>
        internal static string GroupDetail {
            get {
                return ResourceManager.GetString("GroupDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có nhóm.
        /// </summary>
        internal static string GroupEmpty {
            get {
                return ResourceManager.GetString("GroupEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm.
        /// </summary>
        internal static string GroupList {
            get {
                return ResourceManager.GetString("GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        internal static string GroupManage {
            get {
                return ResourceManager.GetString("GroupManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm không thuộc người dùng.
        /// </summary>
        internal static string GroupNotBelongUser {
            get {
                return ResourceManager.GetString("GroupNotBelongUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Nhóm!.
        /// </summary>
        internal static string GroupNotChoose {
            get {
                return ResourceManager.GetString("GroupNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật người dùng thành công!.
        /// </summary>
        internal static string GroupUpdateUserSuccess {
            get {
                return ResourceManager.GetString("GroupUpdateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào.
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã code không hợp lệ.
        /// </summary>
        internal static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang online.
        /// </summary>
        internal static string IsOnline {
            get {
                return ResourceManager.GetString("IsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu này không thể di chuyển lên trên!.
        /// </summary>
        internal static string MenuCanNotMoveUp {
            get {
                return ResourceManager.GetString("MenuCanNotMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa Menu này?.
        /// </summary>
        internal static string MenuConfirmDelete {
            get {
                return ResourceManager.GetString("MenuConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết Menu.
        /// </summary>
        internal static string MenuDetail {
            get {
                return ResourceManager.GetString("MenuDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển Menu thành CM.
        /// </summary>
        internal static string MenuMakeTopic {
            get {
                return ResourceManager.GetString("MenuMakeTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Menu.
        /// </summary>
        internal static string MenuManage {
            get {
                return ResourceManager.GetString("MenuManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa Menu Master này?.
        /// </summary>
        internal static string MenuMasterConfirmDelete {
            get {
                return ResourceManager.GetString("MenuMasterConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao chép MenuMaster.
        /// </summary>
        internal static string MenuMasterCopy {
            get {
                return ResourceManager.GetString("MenuMasterCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết MenuMaster.
        /// </summary>
        internal static string MenuMasterDetail {
            get {
                return ResourceManager.GetString("MenuMasterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền Liên kết.
        /// </summary>
        internal static string MenuMasterGrant {
            get {
                return ResourceManager.GetString("MenuMasterGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết.
        /// </summary>
        internal static string MenuMasterManage {
            get {
                return ResourceManager.GetString("MenuMasterManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Menu Master!.
        /// </summary>
        internal static string MenuMasterNotChoose {
            get {
                return ResourceManager.GetString("MenuMasterNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Menu !.
        /// </summary>
        internal static string MenuNotChoose {
            get {
                return ResourceManager.GetString("MenuNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        internal static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa Module này?.
        /// </summary>
        internal static string ModuleConfirmDelete {
            get {
                return ResourceManager.GetString("ModuleConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết Module.
        /// </summary>
        internal static string ModuleDetail {
            get {
                return ResourceManager.GetString("ModuleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string ModuleManage {
            get {
                return ResourceManager.GetString("ModuleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Module!.
        /// </summary>
        internal static string ModuleNotChoose {
            get {
                return ResourceManager.GetString("ModuleNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di chuyển xuống.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di chuyển lên.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được rỗng!.
        /// </summary>
        internal static string NameCanNotEmpty {
            get {
                return ResourceManager.GetString("NameCanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết đến.
        /// </summary>
        internal static string NavigateTo {
            get {
                return ResourceManager.GetString("NavigateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        internal static string NewPasswordConfirm {
            get {
                return ResourceManager.GetString("NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các tin khác.
        /// </summary>
        internal static string OtherNews {
            get {
                return ResourceManager.GetString("OtherNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang khác.
        /// </summary>
        internal static string OtherPage {
            get {
                return ResourceManager.GetString("OtherPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu chỉnh cấu trúc.
        /// </summary>
        internal static string PageChangeStructure {
            get {
                return ResourceManager.GetString("PageChangeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa trang này?.
        /// </summary>
        internal static string PageConfirmDelete {
            get {
                return ResourceManager.GetString("PageConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao chép.
        /// </summary>
        internal static string PageCopy {
            get {
                return ResourceManager.GetString("PageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết trang.
        /// </summary>
        internal static string PageDetail {
            get {
                return ResourceManager.GetString("PageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang hiển thị.
        /// </summary>
        internal static string PageDisplay {
            get {
                return ResourceManager.GetString("PageDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền Trang.
        /// </summary>
        internal static string PageGrant {
            get {
                return ResourceManager.GetString("PageGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        internal static string PageManage {
            get {
                return ResourceManager.GetString("PageManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn trang!.
        /// </summary>
        internal static string PageNotChoose {
            get {
                return ResourceManager.GetString("PageNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa Panel này?.
        /// </summary>
        internal static string PanelRemoveConfirm {
            get {
                return ResourceManager.GetString("PanelRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm không đúng!.
        /// </summary>
        internal static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đc trống.
        /// </summary>
        internal static string PasswordRequire {
            get {
                return ResourceManager.GetString("PasswordRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật password thất bại!.
        /// </summary>
        internal static string PasswordUpdateFail {
            get {
                return ResourceManager.GetString("PasswordUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật password thành công!.
        /// </summary>
        internal static string PasswordUpdateSuccess {
            get {
                return ResourceManager.GetString("PasswordUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn đến file hiển thị.
        /// </summary>
        internal static string PathToFileDisplay {
            get {
                return ResourceManager.GetString("PathToFileDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn đến file hiệu chỉnh.
        /// </summary>
        internal static string PathToFileModify {
            get {
                return ResourceManager.GetString("PathToFileModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng gõ mã an toàn.
        /// </summary>
        internal static string PleaseTypeCode {
            get {
                return ResourceManager.GetString("PleaseTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Portal.
        /// </summary>
        internal static string PortalManagement {
            get {
                return ResourceManager.GetString("PortalManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa Portlet này?.
        /// </summary>
        internal static string PortletConfirmDelete {
            get {
                return ResourceManager.GetString("PortletConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết Portlet.
        /// </summary>
        internal static string PortletDetail {
            get {
                return ResourceManager.GetString("PortletDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa Portlet này!.
        /// </summary>
        internal static string PortletInstanceConfirmDelete {
            get {
                return ResourceManager.GetString("PortletInstanceConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portlet.
        /// </summary>
        internal static string PortletManage {
            get {
                return ResourceManager.GetString("PortletManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Portlet!.
        /// </summary>
        internal static string PortletNotChoose {
            get {
                return ResourceManager.GetString("PortletNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem hiển thị.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In bài viết.
        /// </summary>
        internal static string PrintArticle {
            get {
                return ResourceManager.GetString("PrintArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý liên hệ.
        /// </summary>
        internal static string ProcessFeedBack {
            get {
                return ResourceManager.GetString("ProcessFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất bản.
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phục hồi.
        /// </summary>
        internal static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phục hồi bài viết.
        /// </summary>
        internal static string RecoverArticle {
            get {
                return ResourceManager.GetString("RecoverArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ.
        /// </summary>
        internal static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu trả lời.
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được trống.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở về.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở về MenuMaster.
        /// </summary>
        internal static string ReturnToMenuMaster {
            get {
                return ResourceManager.GetString("ReturnToMenuMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Nhóm!.
        /// </summary>
        internal static string RoleNotChoose {
            get {
                return ResourceManager.GetString("RoleNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch công tác tuần.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý lịch khoa học.
        /// </summary>
        internal static string ScientificHistory {
            get {
                return ResourceManager.GetString("ScientificHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu trả lời bí mật.
        /// </summary>
        internal static string SecretAnswer {
            get {
                return ResourceManager.GetString("SecretAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi bí mật.
        /// </summary>
        internal static string SecretQuestion {
            get {
                return ResourceManager.GetString("SecretQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Người dùng.
        /// </summary>
        internal static string SecurityManagement {
            get {
                return ResourceManager.GetString("SecurityManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        internal static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        internal static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gởi cho bạn bè.
        /// </summary>
        internal static string SendToFriend {
            get {
                return ResourceManager.GetString("SendToFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình SubDomain.
        /// </summary>
        internal static string SubDomainConfig {
            get {
                return ResourceManager.GetString("SubDomainConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết SubDomain.
        /// </summary>
        internal static string SubDomainDetail {
            get {
                return ResourceManager.GetString("SubDomainDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý giảng viên.
        /// </summary>
        internal static string TeacherManage {
            get {
                return ResourceManager.GetString("TeacherManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục.
        /// </summary>
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục này không thể di chuyển xuống.
        /// </summary>
        internal static string TopicCannotMoveDown {
            get {
                return ResourceManager.GetString("TopicCannotMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục này không thể di chuyển lên.
        /// </summary>
        internal static string TopicCannotMoveUp {
            get {
                return ResourceManager.GetString("TopicCannotMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa Chuyên mục này?.
        /// </summary>
        internal static string TopicConfirmDelete {
            get {
                return ResourceManager.GetString("TopicConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao chép Chuyên mục.
        /// </summary>
        internal static string TopicCopy {
            get {
                return ResourceManager.GetString("TopicCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Chuyên mục thành công.
        /// </summary>
        internal static string TopicDeleteSuccess {
            get {
                return ResourceManager.GetString("TopicDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết Chuyên mục.
        /// </summary>
        internal static string TopicDetail {
            get {
                return ResourceManager.GetString("TopicDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu chỉnh HTML mẫu.
        /// </summary>
        internal static string TopicEditContentTemplate {
            get {
                return ResourceManager.GetString("TopicEditContentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật HTML mẫu cho Chuyên mục thành công.
        /// </summary>
        internal static string TopicEditTemplateSuccess {
            get {
                return ResourceManager.GetString("TopicEditTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền cho Chuyên mục.
        /// </summary>
        internal static string TopicGrant {
            get {
                return ResourceManager.GetString("TopicGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển chuyên mục thành menu.
        /// </summary>
        internal static string TopicMakeMenu {
            get {
                return ResourceManager.GetString("TopicMakeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên mục.
        /// </summary>
        internal static string TopicManage {
            get {
                return ResourceManager.GetString("TopicManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn chuyên mục!.
        /// </summary>
        internal static string TopicNotChoose {
            get {
                return ResourceManager.GetString("TopicNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Chuyên mục.
        /// </summary>
        internal static string TopicSelect {
            get {
                return ResourceManager.GetString("TopicSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu trang.
        /// </summary>
        internal static string TopPage {
            get {
                return ResourceManager.GetString("TopPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thùng rác.
        /// </summary>
        internal static string TrashManage {
            get {
                return ResourceManager.GetString("TrashManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.xuất bản.
        /// </summary>
        internal static string Unpublish {
            get {
                return ResourceManager.GetString("Unpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng thuộc nhóm.
        /// </summary>
        internal static string UserBelongGroup {
            get {
                return ResourceManager.GetString("UserBelongGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa User này?.
        /// </summary>
        internal static string UserConfirmDelete {
            get {
                return ResourceManager.GetString("UserConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết người dùng.
        /// </summary>
        internal static string UserDetail {
            get {
                return ResourceManager.GetString("UserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        internal static string UserManage {
            get {
                return ResourceManager.GetString("UserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được trống.
        /// </summary>
        internal static string UsernameRequire {
            get {
                return ResourceManager.GetString("UsernameRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không thuộc nhóm.
        /// </summary>
        internal static string UserNotBelongGroup {
            get {
                return ResourceManager.GetString("UserNotBelongGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Người dùng!.
        /// </summary>
        internal static string UserNotChoose {
            get {
                return ResourceManager.GetString("UserNotChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truy cập tháng.
        /// </summary>
        internal static string VisitMonth {
            get {
                return ResourceManager.GetString("VisitMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng truy cập.
        /// </summary>
        internal static string VisitTotal {
            get {
                return ResourceManager.GetString("VisitTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chú ý.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Website....
        /// </summary>
        internal static string WebsiteSelect {
            get {
                return ResourceManager.GetString("WebsiteSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuần lễ thứ.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
    }
}
